# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "htcondor2" do |htcondor2|
  	htcondor2.vm.box = "ubuntu/trusty64"
	htcondor2.vm.provision "shell", path: "script.sh"
  	htcondor2.vm.provider :virtualbox do |vb|
		vb.customize [ 'modifyvm', :id, '--memory', '1024' ]
		vb.customize [ 'modifyvm', :id, '--cpus', '2' ]
		vb.customize [ 'modifyvm', :id, '--name', 'htcondor2' ]
  	end
  end
end
